/**
 * Skool Cookie Auto-Refresh Script
 *
 * Checks if Skool cookies are expired and refreshes them automatically.
 * Uses credentials stored in .env.local (SKOOL_EMAIL, SKOOL_PASSWORD).
 *
 * Usage:
 *   bun run scripts/skool-refresh-cookies.ts          # Check and refresh if needed
 *   bun run scripts/skool-refresh-cookies.ts --force  # Force refresh even if valid
 *
 * Can be called from:
 *   - Cron jobs (before sync)
 *   - API routes (on 403 errors)
 *   - Manual terminal
 */

import { chromium, type Cookie } from "playwright";
import { writeFileSync, readFileSync, existsSync } from "fs";
import { resolve } from "path";

const SKOOL_LOGIN_URL = "https://www.skool.com/login";
const TEST_API_URL = "https://api2.skool.com/self/chat-channels?offset=0&limit=1";

interface RefreshResult {
  success: boolean;
  message: string;
  refreshed: boolean;
  expiresAt?: Date;
}

async function loadEnvCredentials(): Promise<{ email: string; password: string } | null> {
  const envPath = resolve(import.meta.dir, "../apps/web/.env.local");

  if (!existsSync(envPath)) {
    return null;
  }

  const envContent = readFileSync(envPath, "utf-8");
  const lines = envContent.split("\n");

  let email = "";
  let password = "";

  for (const line of lines) {
    if (line.startsWith("SKOOL_EMAIL=")) {
      email = line.replace("SKOOL_EMAIL=", "").trim();
    }
    if (line.startsWith("SKOOL_PASSWORD=")) {
      password = line.replace("SKOOL_PASSWORD=", "").trim();
    }
  }

  if (email && password) {
    return { email, password };
  }

  return null;
}

async function loadCurrentCookies(): Promise<string | null> {
  const envPath = resolve(import.meta.dir, "../apps/web/.env.local");

  if (!existsSync(envPath)) {
    return null;
  }

  const envContent = readFileSync(envPath, "utf-8");
  const match = envContent.match(/SKOOL_COOKIES="([^"]+)"/);

  return match ? match[1] : null;
}

async function testCookies(cookies: string): Promise<boolean> {
  try {
    const response = await fetch(TEST_API_URL, {
      headers: {
        accept: "application/json",
        cookie: cookies,
        origin: "https://www.skool.com",
        referer: "https://www.skool.com/",
      },
    });

    return response.ok;
  } catch {
    return false;
  }
}

async function refreshCookies(email: string, password: string): Promise<Cookie[]> {
  console.log("🚀 Launching headless browser...");

  const browser = await chromium.launch({ headless: true });
  const context = await browser.newContext();
  const page = await context.newPage();

  try {
    console.log("📍 Navigating to Skool login...");
    await page.goto(SKOOL_LOGIN_URL, { waitUntil: "networkidle" });

    // Wait for and fill login form
    await page.waitForSelector('input[type="email"], input[name="email"]', { timeout: 10000 });

    const emailInput = await page.$('input[type="email"]') || await page.$('input[name="email"]');
    const passwordInput = await page.$('input[type="password"]');

    if (!emailInput || !passwordInput) {
      throw new Error("Could not find login form fields");
    }

    await emailInput.fill(email);
    await passwordInput.fill(password);

    // Submit
    const loginButton = await page.$('button[type="submit"]');
    if (loginButton) {
      await loginButton.click();
    } else {
      await passwordInput.press("Enter");
    }

    // Wait for redirect
    await page.waitForURL((url) => !url.pathname.includes("/login"), { timeout: 30000 });

    console.log("✅ Login successful!");

    // Get cookies
    const cookies = await context.cookies();
    return cookies.filter(c => c.domain.includes("skool.com") || c.domain.includes("clerk"));

  } finally {
    await browser.close();
  }
}

function saveCookies(cookies: Cookie[]): Date | undefined {
  const scriptDir = resolve(import.meta.dir);
  const projectRoot = resolve(scriptDir, "..");

  // Save as JSON for debugging
  const jsonPath = resolve(scriptDir, ".skool-cookies.json");
  writeFileSync(jsonPath, JSON.stringify(cookies, null, 2));

  // Convert to cookie header format
  const cookieHeader = cookies.map(c => `${c.name}=${c.value}`).join("; ");

  // Update .env.local
  const envPath = resolve(projectRoot, "apps/web/.env.local");
  let envContent = existsSync(envPath) ? readFileSync(envPath, "utf-8") : "";

  // Remove existing SKOOL_COOKIES line
  envContent = envContent
    .split("\n")
    .filter(line => !line.startsWith("SKOOL_COOKIES="))
    .join("\n");

  // Add new cookies
  envContent = envContent.trim() + `\n\n# Skool session cookies (auto-generated by scripts/skool-refresh-cookies.ts)\nSKOOL_COOKIES="${cookieHeader}"\n`;

  writeFileSync(envPath, envContent);

  // Return expiry
  const authToken = cookies.find(c => c.name === "auth_token");
  if (authToken?.expires) {
    return new Date(authToken.expires * 1000);
  }

  return undefined;
}

export async function refreshSkoolCookiesIfNeeded(force = false): Promise<RefreshResult> {
  console.log("🔍 Checking Skool cookies...\n");

  // Load credentials
  const credentials = await loadEnvCredentials();
  if (!credentials) {
    return {
      success: false,
      message: "No credentials found in .env.local (SKOOL_EMAIL, SKOOL_PASSWORD)",
      refreshed: false,
    };
  }

  // Check current cookies
  if (!force) {
    const currentCookies = await loadCurrentCookies();
    if (currentCookies) {
      const isValid = await testCookies(currentCookies);
      if (isValid) {
        console.log("✅ Current cookies are still valid!");
        return {
          success: true,
          message: "Cookies are valid, no refresh needed",
          refreshed: false,
        };
      }
      console.log("⚠️  Cookies expired or invalid, refreshing...\n");
    }
  } else {
    console.log("🔄 Force refresh requested...\n");
  }

  // Refresh cookies
  try {
    const newCookies = await refreshCookies(credentials.email, credentials.password);
    const expiresAt = saveCookies(newCookies);

    console.log(`\n🎉 Cookies refreshed successfully!`);
    if (expiresAt) {
      console.log(`⏰ New cookies expire: ${expiresAt.toLocaleString()}`);
    }

    return {
      success: true,
      message: "Cookies refreshed successfully",
      refreshed: true,
      expiresAt,
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    console.error(`\n❌ Failed to refresh cookies: ${message}`);

    return {
      success: false,
      message: `Failed to refresh: ${message}`,
      refreshed: false,
    };
  }
}

// CLI entry point
if (import.meta.main) {
  const force = process.argv.includes("--force");
  const result = await refreshSkoolCookiesIfNeeded(force);

  if (!result.success) {
    process.exit(1);
  }
}
